site_name: yap
site_url: https://yap.externref.tech
copyright: Copyright &copy; 2024 - now externref
repo_name: externref/yap
repo_url: https://github.com/externref/yap
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  custom_dir: overrides

  font:
    text: Quicksand
    code: Ubuntu Mono
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil 
    view: material/eye

  features:
    - content.action.edit
    - header.autohide

  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

plugins:
  - search
  - blog:
      blog_dir: .
      blog_toc: true
  - social:
      cards_color:
        fill: "#1b1d1f"
  - git-authors
       

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/externref
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/1134016724132446208
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/defsarthak
    - icon: fontawesome/brands/instagram
      link: https://linkedin.com/in/_sarthak.sh